#!/bin/sh

cat > "$CI_PRIMARY_REPOSITORY_PATH/app/Secrets.xcconfig" <<EOF
GENIUS_ACCESS_TOKEN = ${GENIUS_ACCESS_TOKEN}
LASTFM_API_KEY = ${LASTFM_API_KEY}
LASTFM_SHARED_SECRET = ${LASTFM_SHARED_SECRET}
EOF
